# Generated by Django 3.0.6 on 2020-06-02 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='text',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='image',
            new_name='photo',
        ),
    ]
